version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  cars:
    build:
      context: src/cars
      dockerfile: Dockerfile
    ports:
      - "8070:8080"

  rental:
    build:
      context: src/rental
      dockerfile: Dockerfile
    ports:
      - "8060:8080"

  payment:
    build:
      context: src/payment
      dockerfile: Dockerfile
    ports:
      - "8050:8080"


  gateway:
    build:
      context: src/gateway
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8080:8080"
    depends_on:
      - cars
      - rental
      - payment

volumes:
  db-data:
